import { expect,test,type Page } from "@playwright/test";
import { activeCellsFor,fieldShapes,type ShapeId } from "../../app/gameRules";
const mainKey="stillgarden-v4",petKey="stillgarden-gardenkin-v1";
const basePet=(overrides:any={})=>({id:"pet-test",speciesId:"mossbun",name:"Testbun",bornAt:Date.now(),generation:1,parents:[],xp:0,bond:0,genes:{coat:2,accent:2,pattern:1,ears:1,tail:1,bloom:1,size:3,lustre:"plain"},aptitude:5,care:{tend:0,cuddle:0,forage:0,grow:0},activeKnacks:[],...overrides});
const petSave=(pet:any=basePet())=>({version:1,pets:[pet],activePetId:pet.id,selectedPetId:pet.id,eggs:[],discovered:[pet.speciesId],visitor:null,nextVisitorAt:Date.now()+1e9,lurePlant:null,rarePity:0,nestMisses:0,visitorTrust:{},visitorVisits:{}});
async function seed(page:Page,main:any=null,pets:any=null,path="/"){await page.goto(path);await page.evaluate(([m,p])=>{localStorage.clear();if(m)localStorage.setItem("stillgarden-v4",JSON.stringify(m));if(p)localStorage.setItem("stillgarden-gardenkin-v1",JSON.stringify(p));},[main,pets]);await page.reload();}
async function savedMain(page:Page){return page.evaluate(k=>JSON.parse(localStorage.getItem(k)||"null"),mainKey);}
async function savedPets(page:Page){return page.evaluate(k=>JSON.parse(localStorage.getItem(k)||"null"),petKey);}

test.beforeEach(async({page})=>{const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",m=>{if(m.type()==="error")errors.push(m.text());});(page as any).__errors=errors;});
test.afterEach(async({page})=>{expect((page as any).__errors).toEqual([]);});

test("locks scrolling and fits the board on phone tablet and desktop",async({page})=>{for(const size of [{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1366,height:768}]){await page.setViewportSize(size);await seed(page);await expect(page.getByTestId("garden-board")).toBeVisible();const m=await page.evaluate(()=>{const b=document.querySelector('[data-testid="garden-board"]')!.getBoundingClientRect();return{sw:document.documentElement.scrollWidth,sh:document.documentElement.scrollHeight,w:innerWidth,h:innerHeight,left:b.left,top:b.top,right:b.right,bottom:b.bottom};});expect(m.sw).toBeLessThanOrEqual(m.w+1);expect(m.sh).toBeLessThanOrEqual(m.h+1);expect(m.left).toBeGreaterThanOrEqual(0);expect(m.top).toBeGreaterThanOrEqual(0);expect(m.right).toBeLessThanOrEqual(m.w+1);expect(m.bottom).toBeLessThanOrEqual(m.h+1);}});

test("renders every irregular field geometry inside the viewport",async({page})=>{await page.setViewportSize({width:900,height:800});for(const id of Object.keys(fieldShapes) as ShapeId[]){await seed(page,{stage:1,shapeId:id,restored:[]});expect(await page.locator("button[data-cell]").count()).toBe(activeCellsFor(fieldShapes[id]).length);const b=await page.getByTestId("garden-board").boundingBox();expect(b).not.toBeNull();expect(b!.x).toBeGreaterThanOrEqual(0);expect(b!.y).toBeGreaterThanOrEqual(0);expect(b!.x+b!.width).toBeLessThanOrEqual(901);expect(b!.y+b!.height).toBeLessThanOrEqual(801);}});

test("bumps and roots perform their actual mechanics",async({page})=>{await seed(page,{stage:1,shapeId:"classic",restored:[]});await page.locator('button[data-bump="true"][data-restored="false"]').first().click();expect(await page.locator('button[data-restored="true"]').count()).toBeGreaterThan(1);await seed(page,{stage:4,shapeId:"classic",restored:[],crackedRoots:[]});const root=page.locator('button[data-special="roots"]').first();await root.click();await expect(root).toHaveAttribute("data-cracked","true");await expect(root).toHaveAttribute("data-restored","false");await root.click();await expect(root).toHaveAttribute("data-restored","true");});

test("completion advances to a clean persistent next plot",async({page})=>{const active=activeCellsFor(fieldShapes.classic);await seed(page,{stage:1,shapeId:"classic",restored:active.slice(0,-1),completedGardens:0,lifetimeRestored:active.length-1});await page.locator('button[data-cell="'+active[active.length-1]+'"]' ).click();await expect(page.getByText("plot 2")).toBeVisible({timeout:5000});const state=await savedMain(page);expect(state.stage).toBe(2);expect(state.completedGardens).toBe(1);expect(state.restored).toEqual([]);await page.reload();await expect(page.getByText("plot 2")).toBeVisible();});

test("Growhouse planting watering fertilizing harvesting and tools mutate correctly",async({page})=>{const ready=Date.now()-1000;await seed(page,{stage:1,shapeId:"classic",dew:10000,seeds:{clover:4,fern:1},fertilizer:2,plots:[{species:"clover",plantedAt:ready-10000,readyAt:ready,watered:false,fertilized:false}]});await page.getByRole("button",{name:"grow"}).click();await page.getByRole("button",{name:"harvest"}).click();let state=await savedMain(page);expect(state.harvested.clover).toBe(1);expect(state.seeds.clover).toBe(5);await page.getByRole("button",{name:/Cloud Clover/}).first().click();state=await savedMain(page);expect(state.seeds.clover).toBe(4);await page.getByRole("button",{name:"water"}).click();await page.getByRole("button",{name:/feed/}).click();state=await savedMain(page);expect(state.plots[0].watered).toBe(true);expect(state.plots[0].fertilized).toBe(true);expect(state.fertilizer).toBe(1);await page.getByRole("button",{name:"tools + crossing"}).click();await page.getByRole("button",{name:"260 Dew"}).click();state=await savedMain(page);expect(state.shovelLevel).toBe(2);});

test("journal clamps after phone-to-desktop resize",async({page})=>{await page.setViewportSize({width:390,height:844});await seed(page,{stage:1,shapeId:"classic"});await page.getByRole("button",{name:"journal"}).click();for(let i=0;i<25;i++){const later=page.getByRole("button",{name:/later/});if(await later.isEnabled())await later.click();}await page.setViewportSize({width:900,height:800});await expect(page.getByTestId("journal-book").locator("article")).toHaveCount(2);const text=await page.getByTestId("journal-controls").locator("span").textContent();const parts=(text||"").split("/").map(v=>Number(v.trim()));expect(parts[0]).toBeLessThanOrEqual(parts[1]);});

test("malformed main save is normalized without crashing",async({page})=>{await seed(page,{stage:null,dew:null,shapeId:"classic",plots:[{species:"not-real",readyAt:null}],discoveryLog:{clover:{at:null,source:42}},seeds:{clover:null}});await page.getByRole("button",{name:"grow"}).click();await expect(page.getByText("empty pot").first()).toBeVisible();await page.getByRole("button",{name:"journal"}).click();await expect(page.getByTestId("journal-book")).toBeVisible();const state=await savedMain(page);expect(Number.isFinite(state.dew)).toBe(true);expect(state.plots[0].species).toBeNull();});

test("Gardenkin starter rename active companion and guide persist",async({page})=>{await seed(page,null,null,"/pets");await page.getByRole("button",{name:/Mossbun/}).click();await expect(page.getByText("companion record")).toBeVisible();await page.getByRole("button",{name:"rename"}).click();const input=page.locator('input[name="name"]');await input.fill("Juniper");await page.getByRole("button",{name:"keep name"}).click();await expect(page.getByRole("heading",{name:"Juniper"})).toBeVisible();expect((await savedPets(page)).pets[0].name).toBe("Juniper");await page.getByRole("button",{name:"guide"}).click();await expect(page.getByText(/species recorded/)).toBeVisible();});

test("visitor inventory exposes late harvested plants",async({page})=>{const harvested:any={};for(const id of ["clover","fern","poppy","rainmint","moonbell","sunreed","embermoss","pearlgrass","frostvine","blushcap"])harvested[id]=1;await seed(page,{stage:200,completedGardens:199,shapeId:"classic",harvested},petSave(),"/pets");await page.getByRole("button",{name:"visitors"}).click();await expect(page.getByRole("button",{name:"later offerings"})).toBeVisible();await page.getByRole("button",{name:"later offerings"}).click();await expect(page.getByText("Frost Vine")).toBeVisible();await expect(page.getByText("Blush Cap")).toBeVisible();});

test("pet bridge restores soil without resetting player flow",async({page})=>{await seed(page,{stage:1,shapeId:"classic",restored:[]},petSave());await expect(page.getByTestId("gardenkin-field-actor")).toBeVisible();await page.evaluate(()=>window.dispatchEvent(new CustomEvent("stillgarden-pet-restore",{detail:{index:0}})));await expect(page.locator('button[data-cell="0"]')).toHaveAttribute("data-restored","true");await expect(page.getByTestId("garden-board")).toHaveAttribute("data-dragging","false");await expect(page.getByText(/^flow 0$/)).toBeVisible();});

test("pet XP tracking survives a completed plot",async({page})=>{const active=activeCellsFor(fieldShapes.classic);await seed(page,{stage:1,shapeId:"classic",restored:active.slice(0,-1),completedGardens:0,lifetimeRestored:active.length-1},petSave());await page.locator('button[data-cell="'+active[active.length-1]+'"]' ).click();await expect(page.getByText("plot 2")).toBeVisible({timeout:5000});const before=(await savedPets(page)).pets[0].xp;await page.locator('button[data-restored="false"]').first().click();await page.waitForTimeout(400);const after=(await savedPets(page)).pets[0].xp;expect(after).toBeGreaterThan(before);});

test("reduced motion keeps functional pet assistance",async({page})=>{await page.emulateMedia({reducedMotion:"reduce"});const pet=basePet({xp:1e12,activeKnacks:["quickpaws"]});await seed(page,{stage:1,shapeId:"classic",restored:[]},petSave(pet));for(let i=0;i<14;i++){const cell=page.locator('button[data-restored="false"]').first();if(await cell.count())await cell.click();}const immediate=await page.locator('button[data-restored="true"]').count();await page.waitForTimeout(1700);const later=await page.locator('button[data-restored="true"]').count();expect(later).toBeGreaterThan(immediate);});
